### ISSUE TITLE
Reorganize and reformat spec into sphinx docs @ readthedocs

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-schema#19]
**Goal** The current spec is in Google Docs because that format enabled feedback from a broad audience. In order to ensure that the schema and documentation are aligned and version controlled, we will move the spec documentation to the vmc repo. At the same time, the document will be reorganized to make it easier to read.

**Proposal**
* Write document in rst and format with sphinx. Rationale: sphinx, which uses rst markup, provides better support for multi-document linking. (Alternative: Consider recommonmark with sphinx to support markdown, but Reece's intuition is that there will be pitfalls with that approach.)
* Convert Google Doc to rst with pandoc (see comment from @diekhans below).
* Autogenerate versioned docs at readthedocs.

**See also**
[GKS Deliverable Roadmap](https://docs.google.com/presentation/d/1zjZrXuqMEJkAQy82nh5z8UKPKSnl9UKWG17sTO12T08/edit#slide=id.p)

**Comment by diekhans** [comment]
pandoc can do most of this for you :-)

**Comment by reece** [comment]
I'm so glad you suggested that! Using pandoc hadn't occurred to me.

**Comment by reece** [comment]
@ahwagner, @larrybabb:
Progress! vr-schema now contains a docs directory and proposed outline, and commits are built automatically at RTD, as in https://vr-schema.readthedocs.io/en/latest/.

**Comment by ahwagner** [comment]
merging to #53
