### ISSUE TITLE
RFC: Should VMC use Canonical JSON or custom serialization spec?

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-schema#31]
## Background

Objects must be serialized in order to generate a computed identifier. At the time the VMC spec was originally written, there was no widely implemented canonical serialization method. Therefore, a custom serialization method is currently defined in the VMC spec.

In the last two years, the [Canonical JSON](http://wiki.laptop.org/go/Canonical_JSON) quasi-spec has gained a foothold. Implementations exist in python, rust, go, javascript, java at least. (I haven't tested them.) Canonical JSON was created for exactly our purposes: serializing objects in order to compute digests as computed identifiers. 

The [JSON Canonicalization Scheme (JCS)](https://tools.ietf.org/html/draft-rundgren-json-canonicalization-scheme-05) appears to be a more sophisticated standard, under jurisdiction of a standards organization (IETF), but apparently without existing implementations. 

## Question
Moving VMC to use a canonical json structure could provide significant benefits and it may have some risks. Please comment on whether and when we should do so.

**Comment by reece** [comment]
**Benefit** Using CJ or JCS would allow us to remove the discussion serialization from the spec, which would in turn remove a possible source of error in implementation.

**Benefit** Using CJ or JCS would facilitate model changes because we would not need to update serialization specification to agree.

**Risk** Both are nascent standards. Changes to these specs, or differences among implementations, might cause computed identifiers to disagree for the same object. The risk of this is unknown, but intuitively is higher for an evolving spec than for an established spec. This risk would be substantially mitigated by the existing language-neutral tests in the VMC spec.

**Comment by rrfreimuth** [comment]
Thanks for finding these specs.  Nearly any public spec attempting to do this would be better than rolling our own rules, but that doesn't mean they are flawless.  A few comments/questions:

Canonical JSON
1. The wiki page was created in 2007/2008, with the only edit since then being a reference to a JS implementation that was later tagged as not "faithful" to the spec.
2. Do you have any idea whether this proposed spec is consistent with the more recent JSON specs (there appear to be several competing specs in process)?
3. The lexicographical sort appears a bit under-specified.  The wiki page suggests unicode as UTF-8 but does not go further.  Is this a concern for us?
4. Floats are not allowed, so we'd have to represent them as strings. (Not a big deal, but something to be aware of.)

JCS
5. The spec was produced by IETF in May 2018.  This provides significant confidence that it is aligned with evolving JSON specs, which are cross-referenced in the doc itself.
6. The spec has an expiration date of Nov 2018.  Do you know whether it will be refreshed, etc?
7. JCS appears to be more robustly defined and is based on normative standards by the IETF.
8. JCS supports floats but rounds at a given level of precision (per ES6).  As above, just FYI.

My 2 cents:
JCS appears to be more mature, and it is supported by the IETF.  I do not have a sense for its stability, but it seems to have significant advantages over Canonical JSON.  I'd be fine incorporating JCS into VMC, but would recommend reaching out to the developers and asking where it stands.

**Comment by reece** [comment]
@rrfreimuth: The only advantage to Canonical JSON is that implementations exist and they're recent, whereas I can't find any for JCS except what's alluded to in the spec (that refers to ES6 and v8).

I originally linked to the older JCS draft. I updated for draft 5, released Feb 2019.

Sort order does matter. VMC specifies ASCII encoding. IMO, JCS is ambiguous: It says that it's UTF-8 encoded and that keys must be sorted, but it's unclear that keys are sorted in UTF-8 order.

I've contacted the JCS authors to ask about 1) prospects of format changing that would impact id stability, 2) relationship with Canonical JSON, 3) Known implementations.

**Comment by rrfreimuth** [comment]
@reece Sounds good. Thanks for updating the JCS link - great to see that is moving forward.  I'm glad you asked about known implementations, although TBH I'd prefer a spec endorsed by IETF over one that isn't, regardless of implementations.

JCS section 3.2.3 appears to define sorting quite precisely and Appendix A includes code for an example canonicalizer.  I'm sure you've seen those, so I must be missing something WRT the ambiguity you identified.  Perhaps the authors can help on that one.

**Comment by reece** [comment]
I heard back from JCS authors.
The spec and code are here: https://github.com/cyberphone/json-canonicalization

I apparently overlooked the sorting section. Thanks for pointing it out. (It looks quite complicated to me, especially since I think encoding as UTF-16 and sorting the binary result would suffice for a canonical, locale-independent ordering.)

**Comment by reece** [comment]
@rrfreimuth @ahwagner @larrybabb @ronakypatel
 
I spent an hour on a review of many specifications in this area.

My conclusion is that there are many packages and proposals that aspire to a canonical form for json in many languages. There are several proposed standards, but none ratified or de facto winners. Many packages have similar names, which makes it difficult to discern whether they're related or not (often not). Although some packages look like good single-language candidates, none that I found are ready for multi-language use.  Many seem abandoned. The need for a canonical json form is evident, and there was at least one proposal for an ECMA standard.

Therefore, I'm inclined to implement our own serialization format as follows:
* based on json
* keys must be sorted in unicode order
* no "insignificant" whitespace, as defined in [rfc7159§2](https://tools.ietf.org/html/rfc7159#section-2)
* strings must use two-char escapes when available, as defined in [rfc7159§7](https://tools.ietf.org/html/rfc7159#section-7)
* UTF-8 encoded

This is very similar to [Gibson Canonical JSON[(http://gibson042.github.io/canonicaljson-spec/], which, alas, is not the same as the OLPC Canonical JSON discussed at the top of this thread.

I think that meets our needs, can be described easily to implementers, and enables a flexible serialization scheme that is easy to maintain. I think this is likely to also be safe in the sense that any emerging standard would be very likely to make the same decisions.

Please comment before Wed 5/15 with concerns.

**Comment by ahwagner** [comment]
Only concerns are:
* Must be quick to implement
* Must be easy to maintain
  * Wasn't this the primary concern of maintaining our own format?

**Comment by larrybabb** [comment]
I completely trust your judgement @reece. I understand the quandary and agree with @ahwagner that it quick and easy as possible. Deferring to an external approach that may end up never maturing or gaining broad adoption could be worse then going it on our own and waiting to implement the external standard once it becomes more clear.

**Comment by reece** [comment]
Implementation is super quick. For example, python:

```
# make an allele:
>>> from ga4gh.vr import models
>>> a = models.Allele(location=models.SequenceLocation(sequence_id="bogus", interval=models.Interval(start=10, end=11)), state=models.SequenceState(sequence=""))
>>> a.as_dict()
{'location': {'interval': {'end': 11, 'start': 10, 'type': 'SimpleInterval'}, 'sequence_id': 'bogus', 'type': 'SequenceLocation'}, 'state': {'sequence': '', 'type': 'SequenceState'}, 'type': 'Allele'}

# defined cjdump() to return a VR-canonical json format
>>> import json
>>> def cjdump(a): return json.dumps(a, sort_keys=True, separators=(',',':'), indent=None)

# Then:
>>> cjdump(a.as_dict())
'{"location":{"interval":{"end":11,"start":10,"type":"SimpleInterval"},"sequence_id":"bogus","type":"SequenceLocation"},"state":{"sequence":"","type":"SequenceState"},"type":"Allele"}'

```

**Comment by ronakypatel** [comment]
We have our own JSON builder/parser, which is very efficient for generating the JSON for allele registry. Based on your decision, we have to find out ways and implement this canonicalized JSON. If it is just sorting to generate canonical JSON, then, the allele registry response is sorted (i.e. allele registry JSON builder already supports it). We just have to generate VMC JSON and it is going to be sorted.

http://reg.test.genome.network/allele.json?hgvs=NC_000013.10:g.19024100T%3EC

Is there a canonicalize JSON validator available that I can check if this is canonical JSON? In the example that you provide, there are no arrays. If VMC does not have arrays then there are no issues involved. But array canonicalization needs to be checked. 

I think there should be some hashing after the canonicalize JSON is generated.

**Comment by reece** [comment]
Yes, I think the conventions I prescribed above are sufficient.

Arrays should never be sorted by a serializer because that changes the meaning of the array.

The spec will have test cases to demonstrate compliance. And, the major use case for the serialization is to hash it, so we'll definitely have that.

**Comment by rrfreimuth** [comment]
Thanks for looking into this again, @reece .  I defer to you on decisions related to the implementation, but I do have some concerns about rolling our own.

The JCS draft spec appears to be under active development within IETF (https://tools.ietf.org/html/draft-rundgren-json-canonicalization-scheme-05, published Feb 2019 and expires Aug 2019) and in the long run we may decide to adopt that (assuming it becomes a full standard).  Therefore, can you please give me an idea about how your proposed approach aligns with JCS?  If they are compatible, then I'd be fine laying out our own local spec for the short term.  If there are functionally significant differences between the two, then I'd like to understand the nature of those differences.

I'm not trying to slow you down (really), I'm just trying to avoid putting us in the position of implementing breaking changes at a very low level in the spec in the future (especially after it goes through PRC).

**Comment by reece** [comment]
@rrfreimuth : I looked there too when making the suggestion. In a nutshell, I think we should be upward compatible with JCS too.

There's a very minor difference. I was recommending encoding in utf-8 and sorting keys in utf-8 (as VMC did). JCS encodes in utf-8 but sorts in utf-16. That's weird, but the IETF proposal says that do it for compatibility with ECMAScript (which recommends utf-16 apparently) and the proposal also says (paraphrasing) that it'll almost never matter, so use utf-8 if that's all your environment supports. (section 3.2.3)

**Comment by rrfreimuth** [comment]
@reece Thanks for checking.  If that's the only difference, then I'm happy.  Carry on, nothing to see here. :-)

**Comment by reece** [comment]
Question now closed. Will be implemented per https://github.com/ga4gh/vr-schema/issues/31#issuecomment-491962997.
