### ISSUE TITLE
Format of CNV "copies" attribute should be open for unknown, directional changes

### ISSUE THREAD

**Issue by mbaudis** [ga4gh/vr-schema#37]
In the playground, the CNV "copies" attribute is represented through an integer. However, with frequently unknown exact copy number (e.g. high level amplifications, underlying aneuploidy in cancer...), it is necessary to capture relative changes compared to the baseline.

##### Proposal for Discussion:

* Use of an object with both categorical representation (i.e., trough an ontology) and numerical one

```
{
  cn_state: {
    term_id: 'SO:0001742',
    term: 'copy number gain'
  },
  cn_count: 5,
  cn_confidence: {},
  cn_baseline: {}         # the ploidy of the genome being analysed; could e.g. be "1" for X in XY
}

**Comment by reece** [comment]
Please use #46 for a consolidated discussion of CNV requirements.
