### ISSUE TITLE
CNV, STRs, somatic Var Rep Group concept needed?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-schema#39]
CNVs, microsatellites and a variety of somatic variant representations have given rise to the notion of defining a variant grouping that is a set of variant instances (not necessarily equivalent) which can be used to for annotations, assertions, interpretations, evidence collection, etc...

In our modeling to date we have intentionally been focusing on the most atomic representations, rightfully so. However, with the advent of the copy number discussion, we have introduce the notion of providing a range for the quantity of copies for copy number gain variants.  

All previous examples (afaik) have focused on defining a very specific instance of a variant (i.e. allele, haplotype, genotype).  We sort of got into this realm of a "set" or "group" of instances when discussion PGx haplotypes as defined by CPIC/PharmGKB, but we never really resolved the concern.

Question...
To focus on CNVs and micro-satellites for now, what does it mean to specify a range of copy numbers (i,e. from 5 to 20 -or- more than 47)? 

Possible answer..
A CNV instance is a specific number of copies of a given region of a chromosome.  The region of the chromosome that has a non-negative number of copies, is the instance of the sequence. So, to specify a "range" of copies is essentially saying any one of the "instances" in this range belongs in this group.

For example,
If you wanted to specify that a given interpretation is valid for any copy between 4 and 10 of region 1000 to 2000 on chromosome 1 then you are saying that any specific copy instance between 4 copies and 10 copies would be covered by that interpretation.
Interpretation 1...
   Variant Group : NC_00001.10:1000..2000 (4 to 10 copies)
   Pathogenicity: Uncertain Significance

Interpretation 2...
   Variant Group : NC_00001.10:1000..2000 (>10 copies)
   Condition: Condition X
   Pathogenicity: Pathogenic

Case 1 specific finding...
   Variant found: NC_000001.10:1000..20000 (6 copies)
   Result: interp 1 above matches and the assertion may potentially be used to inform the patient's results.

Case 2 specific finding...
    Variant found: NC_000001.10:1000..2000 (20 copies)
    Result: interp 2 above matches and the assertion may potentially be used to inform the patient's results.

Hopefully, this highlights the distinction between defining "variants" that are "sets" or "groups"  verses "instances" and the need to be able to do both in order to collect knowledge and associate it with actual findings.

This can also be applied to microsatellites, which are short tandem repeats that often get expressed as a range as well as in the HTT gene for Huntington's disease. see [ClinVar NM_002111.6(HTT):c.52CAG(27_35)](https://www.ncbi.nlm.nih.gov/clinvar/variation/31915/). 

Individual assay findings produce a specific count of the tandem repeats and then determine if the fall into the variant group defined by NM_002111.6(HTT):c.52CAG(27_35) or some other group that may have a different interpretation.

As we explore variant representations, let's determine if we need to be separating the notion of atomic, specific, instance representations from group or set representations and provide a clean separation, if so.

**Comment by reece** [comment]
Please use #46 for a consolidated discussion of CNV requirements.
