### ISSUE TITLE
Floating point copy number

### ISSUE THREAD

**Issue by ronakypatel** [ga4gh/vr-schema#41]
I observed this dbVar entry with floating point copy number. 

I am not sure how accurate this study is or what is the logic of showing floating point copy number, but, if this is persistent then we need to take care of it.

https://www.ncbi.nlm.nih.gov/dbvar/variants/nsv3169357/#VariantDetails

**Comment by reece** [comment]
Please use #46 for a consolidated discussion of CNV requirements.
