### ISSUE TITLE
Total Copy/Genomic Count concept and HGVS

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-schema#42]
This is a copy and paste from an email thread initiated by Peter Causey-Freeman...

==== From 9/26/2018 ====

My colleague, Raymond Dalgleish and I have been asked to advise regarding HGVS descriptions in which the term dup (duplication) is being used to describe increases in the copy number of a specified range of genomic sequence. The problem is that dup is intended as the description of a tandem duplication of sequence, so its use in these circumstances is inappropriate because the additional copies of a described genomic region sequence would be alleles of a different genomic loci. If I remember correctly, you have views on this issue relating to the VMC model.

Raymond is a full member of the HGVS SVN working group. He recently attended a meeting concerning the best practice for variant reporting in DMD. At the meeting he was asked whether there was an HGVS compliant way to describe the total count for individual exons, for example DMD gene exons identified by MLPA (https://en.wikipedia.org/wiki/Multiplex_ligation-dependent_probe_amplification ). When Raymond and I discussed the issue, I remembered the VarRep discussions about the potential use of a total genome count object within the VMC model. Raymond and I want to propose a similar object/variant description for adoption by the HGVS and it would make sense to use similar terminology. What we need is a 3 letter description for the variant type e.g. dup = duplication, ins = insertion. **Have you chosen a term for use in VMC? If not, we were thinking about proposing tcc = total copy count or tgc = total genomic count.**

Do you have any comments or thoughts on the issue.

Best wishes,

Peter Causey-Freeman

**Comment by reece** [comment]
Please use #46 for a consolidated discussion of CNV requirements.
