### ISSUE TITLE
Question about CNVs with additional alterations

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-schema#45]
Conversation with @ratsch today described a requirement for consideration under our current model:

Given a Copy Number Gain (n=5), how to represent an alteration that occurs on only some of the copies (e.g. a SNV found on 2 of the copies)? One proposed way is to represent a CNV as a collection of haplotypes, where each haplotype represents either an altered or unaltered copy.

A second approach could be to optionally specify a genotype within a CNVState to represent this complexity.

**Comment by reece** [comment]
Please use #46 for a consolidated discussion of CNV requirements.
