### ISSUE TITLE
Write fusion requirements document

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-schema#51]
The goal for this issue is to write a single document with fusion use cases and a proposed model.

This should also serve as an introductory exercise for handling ambiguous representations of fusions (e.g. only one fusion partner specified or only gene names specified) alongside particular representations of fusions (defined transcript regions present / absent).

**Comment by reece** [comment]
This is the same as #28, right? If so, please close this issue.

**Comment by ahwagner** [comment]
This issue is about representing transcript and gene fusions specifically, motivated by the requirements of the ClinGen somatic working group. This is obviously an overlapping scope with #28, though there are some differences:

Translocations cause some fusions, but translocations themselves will have additional and distinct requirements that fusions will not, e.g. specifying genomic insertion coordinates and orientation.

Fusions will also have distinct rule-based considerations that don't fall under the scope of "translocations and junctions", e.g. one-partner rule-based variation descriptions.

However, I have no objection to merging this as a sub-issue of #28 if we want to keep tickets in this repo high level, especially as the notion of _junctions_ are a necessary component for representing particular fusions. @reece I'll leave decision to merge to your discretion.

**Comment by reece** [comment]
Okay. Closing so that all of the multi-location thinking is captured in one place.
